### PR TITLE
Remove grpc-throughputlb package

### LINKED ISSUE #424: throughputlb is deprecated
The `throughputlb` package uses the old grpc balancer, which was deprecated in a later version of gRPC (v1.30.0+). If we want to bump the grpc module in the future, we will have to rewrite our code to make use of the new `google.golang.org/grpc/balancer` package.

### PR DESCRIPTION
**Pull request by ctlong**
Closes #424.

cc/ @mkocher

### CODE REVIEW

**Review by mkocher — APPROVED** [review]
+6/-499, pretty sweet

**Review by mkocher — DISMISSED** [review]
LGTM

**Review by mkocher — APPROVED** [review]
Unleash the CI daemons

**Comment by ctlong** [comment]
> +6/-499, pretty sweet

Try +122,000/-97,000 :dizzy_face:

**Review by mkocher — APPROVED** [review]
I have to admit I didn't read ever one of the 122k lines.

**Comment by ctlong** [comment]
We wanted to test the performance of this a little bit. We deployed this to a new cf-deployment environment and spun up some log spewers getting the dopplers to about 20% CPU usage. The CPU usage on the old and new code was nearly identical - when we looked closely we could see the unmarshalling was a bit faster and marshalling was a bit slower and overall they balanced out.

-- @mkocher & Carson

**Pull request merged**
