### PR TITLE
[Bionic update] Replace "killall" with "pkill"

### PR DESCRIPTION
**Pull request by jochenehret**
* the Bionic stemcell comes with killall in version 23.1 which suffers
  from https://gitlab.com/psmisc/psmisc/-/issues/23
* use pkill instead which works on Xenial as well as Bionic

### CODE REVIEW

**Comment by friegger** [comment]
@selzoc Can we expect a release containing this fix soon?

**Comment by selzoc** [comment]
Funnily enough, when we looked into this, we found that many of these control scripts are no longer used due to BPM being the driver https://github.com/cloudfoundry/loggregator-release/commit/f385d757586345b3c49a42bd51fc92ac4153be32

However, the drain scripts have been updated with this change and appear to work well.

We can cut a release sometime in the next few weeks.

**Comment by bkrannich** [comment]
@selzoc, @emalm: Any chance to accelerate cutting a new release here (or, if that's easier patching the release that's currently out with this fix only)? As mentioned in our call with David Stevenson, Eric and others, this is one of two outstanding fixes we would need to validate cf-deployment with Bionic. Thanks in advance.

**Comment by dsboulder** [comment]
Understood. @selzoc and I have chatted some about doing it faster due to the bionic timing. We'll update this thread.

**Comment by selzoc** [comment]
https://github.com/cloudfoundry/loggregator-release/releases/tag/v106.5.0

**Pull request merged**
